apiVersion: v1
kind: Service
metadata:
  name: nginx-phpfpm
  namespace: testci
  labels:
    app: nginx-phpfpm
spec:
  selector:
    app: nginx-phpfpm
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
